---
spring:
  profiles: local
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
wert-aus-git-application-yml: local profile selected
  
---
spring:
  profiles: test
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
wert-aus-git-application-yml: test profile selected